#!/bin/sh
# Scans midi/music/*.mid and midi/sfx/levelup.mid, embeds each as a C byte
# array via `xxd -i`, and writes generated/music_tracks.h - an aggregator
# that #includes every per-track header and lists them in kMusicTracks[]
# so the game can shuffle across however many tracks are in midi/music.
#
# Re-run this whenever you add/remove/rename a .mid file. CMake re-runs it
# automatically (see CMakeLists.txt); compile.sh runs it every time.
set -e

ROOT_DIR="$(cd "$(dirname "$0")" && pwd)"
MUSIC_DIR="$ROOT_DIR/midi/music"
SFX_DIR="$ROOT_DIR/midi/sfx"
OUT_DIR="$ROOT_DIR/generated"

if ! command -v xxd >/dev/null 2>&1; then
    echo "generate_midi_headers.sh: xxd not found (try: apt install xxd)" >&2
    exit 1
fi

mkdir -p "$OUT_DIR"

# Turns a filename into a valid, collision-safe C identifier:
# "Entry of the Gladiators!.mid" -> "trk_Entry_of_the_Gladiators_"
sanitize() {
    base=$(basename "$1")
    base="${base%.*}"
    echo "$base" | sed -E 's/[^A-Za-z0-9_]/_/g'
}

# ---- music/*.mid -> generated/music_tracks.h (shuffle-able playlist) ----
AGG="$OUT_DIR/music_tracks.h"
{
    echo "// Auto-generated by generate_midi_headers.sh - do not edit by hand."
    echo "#pragma once"
    echo
} > "$AGG"

count=0
entries=""
if [ -d "$MUSIC_DIR" ]; then
    for f in "$MUSIC_DIR"/*.mid; do
        [ -e "$f" ] || continue
        name=$(basename "$f")
        ident="trk_$(sanitize "$f")"
        xxd -i -n "$ident" "$f" > "$OUT_DIR/${ident}.h"
        echo "#include \"${ident}.h\"" >> "$AGG"
        entries="${entries}    { ${ident}, ${ident}_len, \"${name}\" },
"
        count=$((count + 1))
    done
fi

{
    echo
    echo "struct EmbeddedMidiTrack { const unsigned char* data; unsigned int len; const char* name; };"
    echo "static const EmbeddedMidiTrack kMusicTracks[] = {"
    printf '%s' "$entries"
    echo "};"
    echo "static const int kMusicTrackCount = $count;"
} >> "$AGG"

echo "generate_midi_headers.sh: embedded $count music track(s) into generated/music_tracks.h"

# ---- sfx/levelup.mid -> generated/sfx_levelup_mid.h (fixed name/symbol) ----
LEVELUP="$SFX_DIR/levelup.mid"
if [ -f "$LEVELUP" ]; then
    xxd -i -n bb_sfx_levelup_mid "$LEVELUP" > "$OUT_DIR/sfx_levelup_mid.h"
    echo "generate_midi_headers.sh: embedded $LEVELUP -> generated/sfx_levelup_mid.h"
else
    echo "generate_midi_headers.sh: warning: $LEVELUP not found - level-up SFX will be silent" >&2
    {
        echo "// $LEVELUP was missing at generate time - empty stub so the build still links."
        echo "#pragma once"
        echo "static const unsigned char bb_sfx_levelup_mid[] = { 0 };"
        echo "static const unsigned int bb_sfx_levelup_mid_len = 0;"
    } > "$OUT_DIR/sfx_levelup_mid.h"
fi
